# 기본 이미지 설정
FROM python:3.11.6

# 작업 디렉토리 설정
WORKDIR ./tookie-BE

# 의존성 파일 복사 및 설치
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 애플리케이션 코드 복사
COPY . .

# 애플리케이션 실행
CMD ["python", "./init_db.py"]
CMD ["uvicorn", "app:app", "--host", "localhost", "--port", "3000", "--reload"]