"""생년월일추가

Revision ID: 4e0a57008d47
Revises: ed3369949311
Create Date: 2024-08-09 06:10:59.139732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4e0a57008d47'
down_revision: Union[str, None] = 'ed3369949311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('investment_preferences', 'investment_goal',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='investmentgoal'),
               nullable=False)
    op.drop_column('investment_preferences', 'investment_horizon')
    op.drop_column('investment_preferences', 'risk_preference')
    op.add_column('users', sa.Column('birthdate', sa.String(), nullable=False))
    op.alter_column('users', 'phone_number',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'gender',
               existing_type=mysql.ENUM('MALE', 'FEMALE'),
               nullable=False)
    op.alter_column('users', 'investment_level',
               existing_type=mysql.ENUM('Beginner', 'Intermediate', 'Advanced'),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'investment_level',
               existing_type=sa.Integer(),
               type_=mysql.ENUM('Beginner', 'Intermediate', 'Advanced'),
               existing_nullable=True)
    op.alter_column('users', 'gender',
               existing_type=mysql.ENUM('MALE', 'FEMALE'),
               nullable=True)
    op.alter_column('users', 'phone_number',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_column('users', 'birthdate')
    op.add_column('investment_preferences', sa.Column('risk_preference', mysql.ENUM('LOW', 'MEDIUM', 'HIGH'), nullable=False))
    op.add_column('investment_preferences', sa.Column('investment_horizon', mysql.ENUM('SHORT_TERM', 'MEDIUM_TERM', 'LONG_TERM'), nullable=False))
    op.alter_column('investment_preferences', 'investment_goal',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='investmentgoal'),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
